# Generated by Django 3.2.4 on 2021-06-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210622_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_id',
        ),
    ]
