# Generated by Django 3.2.4 on 2021-06-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='item_picture',
            field=models.ImageField(default='default.jfif', upload_to='homeImg'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='transaction_state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
