# Generated by Django 3.2.4 on 2021-06-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210622_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
