# Generated by Django 3.2.4 on 2021-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('1', 'Single Family Home'), ('2', 'Condominium'), ('3', 'Apartment'), ('4', 'Town Home'), ('5', 'Duplex'), ('6', 'Loft')], max_length=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_state',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processing'), ('3', 'Available'), ('4', 'Closed'), ('5', 'Sold')], max_length=2),
        ),
    ]
